version: "3.8"
services:
  server:
    build: .
    image: social-network-server
    ports:
      - 4000:4000
    environment: 
      DATABASE_NAME: social_network_repo
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: socialsecret
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    depends_on: 
      - postgres
  postgres:
    image: postgres:13
    volumes:
      - social-network-server-data:/var/lib/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: socialsecret
      POSTGRES_DB: social_network_repo
    ports:
      - '5432:5432'
volumes:
  social-network-server-data: